/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as ResolutionRouteImport } from './routes/resolution'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as TypographyRouteImport } from './routes/typography'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolutionRoute = ResolutionRouteImport.update({
  id: '/resolution',
  path: '/resolution',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const TypographyRoute = TypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/positions': typeof PositionsRoute
  '/resolution': typeof ResolutionRoute
  '/strategies': typeof StrategiesRoute
  '/typography': typeof TypographyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/positions': typeof PositionsRoute
  '/resolution': typeof ResolutionRoute
  '/strategies': typeof StrategiesRoute
  '/typography': typeof TypographyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/positions': typeof PositionsRoute
  '/resolution': typeof ResolutionRoute
  '/strategies': typeof StrategiesRoute
  '/typography': typeof TypographyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/positions' | '/resolution' | '/strategies' | '/typography'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/positions' | '/resolution' | '/strategies' | '/typography'
  id:
    | '__root__'
    | '/'
    | '/positions'
    | '/resolution'
    | '/strategies'
    | '/typography'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PositionsRoute: typeof PositionsRoute
  ResolutionRoute: typeof ResolutionRoute
  StrategiesRoute: typeof StrategiesRoute
  TypographyRoute: typeof TypographyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resolution': {
      id: '/resolution'
      path: '/resolution'
      fullPath: '/resolution'
      preLoaderRoute: typeof ResolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typography': {
      id: '/typography'
      path: '/typography'
      fullPath: '/typography'
      preLoaderRoute: typeof TypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PositionsRoute: PositionsRoute,
  ResolutionRoute: ResolutionRoute,
  StrategiesRoute: StrategiesRoute,
  TypographyRoute: TypographyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
